In [2]:
def sign (x):
    if x>0: 
        return 'Positive'
    elif x<0: 
        return 'Negative'
    else:
        return 'Zero'

for x in [-1, 0 , 1]:
    print (sign(x))
    

Negative
Zero
Positive


In [17]:
#Numpy

In [3]:
import numpy as np

In [6]:
a = np.array([1, 2,3])
print (type(a), a[0], a[1], a[2])
a[0]= 5
print (a)

<class 'numpy.ndarray'> 1 2 3
[5 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]]) # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [10]:
a = np.zeros((2,2)) # Create an array of all zeros print(a)
b = np.ones((1,2)) # Create an array of all ones print(b)
c = np.full((2,2), 7) # Create a constant array
print (c)

[[7 7]
 [7 7]]


In [13]:
d = np.eye(2)
print (d)

[[1. 0.]
 [0. 1.]]


In [15]:
e= np.random.random((2,2))
print (e)

[[0.82706048 0.76230902]
 [0.44414816 0.15134371]]


In [16]:
#Array Indexing

In [24]:
a1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a1)
b1 = a1[:2, 1:3]
print ('\n',b1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[2 3]
 [6 7]]


In [23]:
#Playing With row functions

In [25]:
row_r1 = a1[1, :] # Rank 1 view of the second row of a
row_r2 = a1[1:2, :] # Rank 2 view of the second row of a
row_r3 = a1[[1], :] # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [26]:
#Playing with Columns

In [27]:
col_r1 = a1[:, 1]
col_r2 = a1[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [31]:
a2 = np.array([[1,2], [3, 4], [5, 6]])
print ("Array \n\n", a2, "\n")

print(a2[[0, 1, 2], [0, 1, 0]])

print(np.array([a2[0, 0], a2[1, 1], a2[2, 0]]))

print(a2[[0, 0], [1, 1]])

print(np.array([a2[0, 1], a2[0, 1]]))

Array 

 [[1 2]
 [3 4]
 [5 6]] 

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [33]:

bool_idx = (a2 > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [34]:
#Data Types

In [35]:
x = np.array([1, 2]) # Let numpy choose the datatype
y = np.array([1.0, 2.0]) # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64) # Force a particular datatype
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [36]:
#Array Math

In [37]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
print ("Subtraction \n")
print(x - y)
print(np.subtract(x, y))

Subtraction 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [40]:
print("Multiplication\n\n", np.multiply(x, y))

Multiplication

 [[ 5. 12.]
 [21. 32.]]


In [41]:
print("Division\n\n",np.divide(x, y))

Division

 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
print ('Squrare Root of X\n\n', np.sqrt (x))

Squrare Root of X

 [[1.         1.41421356]
 [1.73205081 2.        ]]
